### PR TITLE
update docs

### PR DESCRIPTION
**Pull request by janmejayamet**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Closing and reporting for not getting the t-shirt with this useless PR.

**Comment by janmejayamet** [comment]
> Closing and reporting for not getting the t-shirt with this useless PR.

still got the t shirt , LOL

**Comment by pedrobaeza** [comment]
Don't get it as something sure:

https://hacktoberfest.digitalocean.com/hacktoberfest-update

The time you spend in this is the same as doing a real contribution.

**Comment by janmejayamet** [comment]
> Don't get it as something sure:
> 
> https://hacktoberfest.digitalocean.com/hacktoberfest-update
> 
> The time you spend in this is the same as doing a real contribution.

My 4 pull request are updated and will receive it by the end of the month , LMAO (Better Luck Next Time) , should learn to help someone out. Look who's Laughing now?

**Pull request closed without merging**
