### PR TITLE
[11.0][ADD] website_theme_flexible

### PR DESCRIPTION
**Pull request by tarteo**
This theme is exceptionally configurable.
You can set the colors, fonts and layout you want (not limited by presets).

https://github.com/OCA/website/pull/421

### CODE REVIEW

**Comment by Fuchur777** [comment]
@rgarnau & @simahawk can you "re"-review.

**Review by HviorForgeFlow — APPROVED** [review]
LGTM :+1:

**Comment by pedrobaeza** [comment]
@tarteo do you want to keep the 4 commits?

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
I'd say we can squash them

**Comment by tarteo** [comment]
@pedrobaeza No, I squashed them.

**Comment by simahawk** [comment]
merging as was already reviewed more times here https://github.com/OCA/website/pull/421

**Pull request merged**
