### PR TITLE
improved docs

### PR DESCRIPTION
**Pull request by sidhantsharmaa**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Closing and reporting for not getting the t-shirt with this useless PR.

**Comment by maxhumber** [comment]
Wow. You are getting lit up with garbage. Sorry man :/ 

I found this repo because one of the bots that attacked you attacked me.

If you just add the label "Spam" (on the right hand side) to this PR it won't count for the shirt.

**Comment by pedrobaeza** [comment]
Thanks for the info. I will try that.

**Comment by pedrobaeza** [comment]
I have added it, but it doesn't exist as something "standard", as I needed to create it. Do you think is enough?

**Comment by maxhumber** [comment]
Awesome! That's all you have to do! 

Per the Hacktoberfest docs:

```
Legend

Invalid
Your PR has been labeled as "invalid" or "spam" by a maintainer and won't count toward winning Hacktoberfest.
```

Link: https://hacktoberfest.digitalocean.com/profile

#fightback

**Comment by pedrobaeza** [comment]
Thank you very much. Information very useful.

**Pull request closed without merging**
